controller_manager:
  ros__parameters:
    panda_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

gravity_compensation_example_controller:
  ros__parameters:
    robot_type: panda

joint_impedance_example_controller:
  ros__parameters:
    robot_type: panda

cartesian_impedance_example_controller:
  ros__parameters:
    arm_id: panda

panda_joint_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 0.5
